import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SocketProvider from "../../providers/SocketProvider";
import StoreProvider from "../../providers/StoreProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Ruthi Meeting App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <SocketProvider>
            <main className="flex flex-col min-h-screen bg-secondary">
              {children}
            </main>
          </SocketProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
